FROM debian:bullseye

RUN apt update && \
    apt install -y mariadb-server php-fpm php-mysql python3-certbot-nginx && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
# a modifier
CMD [ "mysqld" ]