FROM debian:bullseye

RUN apt update && \
    apt install -y mariadb-server netcat && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/mysqld && chown -R  mysql:mysql /run/mysqld && chmod 777 /run/mysqld

COPY init.sql /docker-entrypoint-initdb.d/
COPY my.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

USER mysql

CMD [ "mysqld" ]