CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER ${WORDPRESS_DB_USER}@'%' IDENTIFIED BY ${WORDPRESS_DB_PASSWD};
GRANT ALL PRIVILEGES ON wordpress.* TO ${WORDPRESS_DB_USER}@'%';
SELECT user, host FROM mysql.user;
FLUSH PRIVILEGES;