services:
  nginx:
    build:
      context: ./Nginx
      dockerfile: dockerfile
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build:
      context: ./WordPress
      dockerfile: dockerfile
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build:
      context: ./MariaDB
      dockerfile: dockerfile
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
volumes:
  wordpress_data:
  mariadb_data:
networks:
  inception:
    driver: bridge